### ISSUE TITLE
Status variables are blank – any ideas?

### ISSUE THREAD

**Issue by rileyjshaw** [robhurring/tmux-spotify#4]
Hi! I just moved onto a new Macbook running Mojave 10.14.6. I used this plugin on my prior computer with the same OS, [.tmux.config](https://github.com/rileyjshaw/.supermac/blob/master/.tmux.conf#L16), and terminal ([iTerm2 config](https://github.com/rileyjshaw/.supermac/blob/master/configs/iterm/com.googlecode.iterm2.plist)) with no problems. On my fresh install, the status variables are blank

I've gone through the [scripts directory](https://github.com/robhurring/tmux-spotify/tree/master/scripts) and ran the individual osascript calls from a tmux shell, and they return the correct values when run manually.

Do you have any ideas about what I should try next? I'm getting no errors, warnings, or privacy/permission prompts, and this configuration worked on my previous two laptops.

I've tried reinstalling the plugin, and reinstalling Spotify (both Homebrew and manual installs) to no avail.

Thanks!

**Comment by rileyjshaw** [comment]
I just tried reinstalling Spotify manually in case it was a Homebrew permissions issue. No dice – the status variables are still blank.

**Comment by jcypret** [comment]
@rileyjshaw I ran into a similar issue but was able to get it working by [using the new variables names](https://github.com/jcypret/dotfiles/commit/492764aeff7a3c7cfad506ccc4232df0abd21f42). It looks like backwards compatibility was added to this plugin (https://github.com/robhurring/tmux-spotify/commit/dc8e4d2b729b8c1445197fff0cb98d8e5debc85a) but I can only get the new variables to work on my machine.

**Comment by rileyjshaw** [comment]
Amazing, thanks for pointing out the new variable names @jcypret! I also needed to apply [this PR to `artists.sh`](https://github.com/robhurring/tmux-spotify/pull/6/commits/c0f8fce44bc17eb1ab0183303407335ba1db6174) to get the artist showing up properly, but it's all working smoothly now. Thanks again!
