### ISSUE TITLE
Only display when playing

### ISSUE THREAD

**Issue by timtyrrell** [robhurring/tmux-spotify#7]
Any idea how to _not_ display any of the status when nothing is playing? I am trying to use the tmux conditional `?` but failing. Example below of my flailing around. Also, feel free to close this issue, thanks.

`set -g status-right '#{?#{music_status},♫ #{music_status} #{artist}: #{track} |,}'`

**Comment by alejandrodnm** [comment]
`music_status` is always defined, it defaults to `paused_icon`

https://github.com/robhurring/tmux-spotify/blob/ccd5fde1ed90e45be32eb259f0651106f2d106ee/scripts/status.sh#L27-L37

Try changing `music_status` to `track`

This works for me 

```
tm_tunes="#[fg=$tm_color_music] #{?#{track},#{track} #{tm_separator_right_thin} #{artist} #{tm_separator_right_thin} #{album},}"

set -g status-right $tm_tunes' '$tm_hour' '$tm_cpu' '$tm_battery
```

**Comment by timtyrrell** [comment]
@alejandrodnm Thanks for answering. Take a look at this if you can, it is like `track` isn't output if I also used as a variable, see anything silly I am doing? I just checked and I am up to date with the latest code.


<img width="1014" alt="Screen Shot 2022-02-21 at 5 57 03 PM" src="https://user-images.githubusercontent.com/100535/155044793-91a265a8-5e2c-4abf-9acf-0a9d884e2b5c.png">


<img width="1016" alt="Screen Shot 2022-02-21 at 5 57 33 PM" src="https://user-images.githubusercontent.com/100535/155044784-5feea24b-0adb-41b8-98bf-e43b32cf138b.png">

**Comment by alejandrodnm** [comment]
Sorry @timtyrrell I didn't realize that I had the same problem as you. Yeah, for some reason once you read the variable it's no longer available.

I have a different issue in that I want have the music information in a different status row and I had to manually call the scripts or the variables would just be empty:

```
set -g status 2
tm_tunes="#[fg=$tm_color_music] #(/Users/adonascimento/.tmux/plugins/tmux-spotify/scripts/track.sh) #{tm_separator_right_thin} #(/Users/adonascimento/.tmux/plugins/tmux-spotify/scripts/artist.sh) #{tm_separator_right_thin} #(/Users/adonascimento/.tmux/plugins/tmux-spotify/scripts/album.sh)"
set -g status-format[1] '#[align=right]'$tm_tunes
```
https://github.com/alejandrodnm/tmux-colors-nick/blob/master/tmuxcolors-nick.conf#L59-L71

So now my definition is super ugly, but I don't want to go through this rabbit hole. Maybe you can try something similar.

Sorry for the fake news :(

**Comment by timtyrrell** [comment]
@alejandrodnm Looks like reassigning it gets around the issue 😎 Thanks for the support.

```
tm_tunes_present="#{track}"
tm_tunes="#{?#{tm_tunes_present},#{track} #{artist},}"
set -g status-right $tm_tunes
```
<img width="1061" alt="Screen Shot 2022-02-22 at 7 02 36 AM" src="https://user-images.githubusercontent.com/100535/155147756-f878f9e9-8b2c-46bb-8eda-61c20d50aa1c.png">
